#pragma once
#include <cstdint>
#include <cstddef>
#include <vector>
#include <memory>
#include "rect.h"
#include "color.h"
#include "screen_span.h"
#include "element_base.h"
#include "elements.h"
#include "elements/pixel.h"
